# _config.yml
#
# This file is very important. It contains:
# - Metadata that is important for SEO
# - Links to social media, where you can add new links for free, and they will be rendered nicely
# - Some basic color settings
# - The main project settings

## Site metadata
title: CoRoLab UoM
email: corolabuom@gmail.com
description: "Cognitive Robotics Lab at University of Manchester"
## Postal address (add as many lines as necessary)
address:
  - line: Kilburn Building
  - line: University of Manchester, Oxford Rd
  - line: Manchester M13 9PL

## Social media usernames (many available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/corolab_uom
  - title: github
    url: http://github.com/corolab
  - title: envelope
    url: mailto:corolabuom@gmail.com

## Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6b3090
  secondary: 783a9c
  secondary-dark: 000

## Build settings
markdown: kramdown
permalink: pretty

## Collections
collections:
    students:
        title: Students
        output: true
    postdocs:
        title: Postdocs
        output: true
    alumni:
        title: Alumni
        output: true
    visitors:
        title: Visitors
        output: true
collections_dir: _members